/**
 * One connected dispatch record per shipment.
 * Dispatch ID is permanent and always links back to Clearance ID,
 * Payment Request ID and Project ID — never duplicated on return,
 * correction or rescheduling.
 */
export type DispatchStatus =
  | "clearance_received"
  | "logistics_accepted"
  | "items_checked"
  | "packing_assigned"
  | "packing_submitted"
  | "packing_completed"
  | "dispatch_planned"
  | "booked_externally"
  | "dispatched"
  | "delivered"
  | "closed"
  | "info_required"
  | "item_unavailable"
  | "packing_correction"
  | "dispatch_delayed"
  | "delivery_issue"
  | "returned"
  | "cancelled"
  | "suspended";

export type DelayOwner = "accounts" | "items" | "packing" | "transporter" | "franchise" | "logistics";

export type ExternalBooking = {
  service: "Shiprocket" | "WheelsEye" | "Other";
  bookingId: string;
  awbOrLr: string;
  transporter: string;
  vehicle?: string;
  driverName?: string;
  driverMobile?: string;
  bookingDate: string;
  dispatchDate?: string;
  trackingUrl: string;
  expectedDelivery: string;
};

export type DispatchRecord = {
  dispatchId: string;
  clearanceId: string;
  paymentRequestId: string;
  projectId: string;
  store: string;
  city: string;
  items: number;
  qty: number;
  clearanceDate: string;
  requiredDelivery: string;
  launchDate: string;
  status: DispatchStatus;
  priority: "urgent" | "high" | "normal";
  priorityReason: string;
  accountsVerified: boolean;
  packingAssignee: string | null;
  packingDue: string | null;
  packingEvidence: boolean;
  booking: ExternalBooking | null;
  deliveredOn: string | null;
  proof: boolean;
  issue: string | null;
  delayOwner: DelayOwner | null;
};

export type PackingStaff = {
  id: string;
  name: string;
  initials: string;
  active: number;
  dueToday: number;
  completed: number;
  corrections: number;
};

export const TODAY = "2026-08-05";

export const DISPATCHES: DispatchRecord[] = [
  {
    dispatchId: "DSP-000121",
    clearanceId: "CLR-1041",
    paymentRequestId: "PR-000318",
    projectId: "PRJ-000018",
    store: "Clean Craft Jaipur",
    city: "Jaipur",
    items: 42,
    qty: 96,
    clearanceDate: "2026-08-03",
    requiredDelivery: "2026-08-11",
    launchDate: "2026-08-18",
    status: "clearance_received",
    priority: "urgent",
    priorityReason: "Accounts clearance unaccepted for 2 days and launch is 13 days away.",
    accountsVerified: true,
    packingAssignee: null,
    packingDue: null,
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: "logistics",
  },
  {
    dispatchId: "DSP-000122",
    clearanceId: "CLR-1042",
    paymentRequestId: "PR-000321",
    projectId: "PRJ-000019",
    store: "Clean Craft Indore",
    city: "Indore",
    items: 36,
    qty: 74,
    clearanceDate: "2026-08-04",
    requiredDelivery: "2026-08-09",
    launchDate: "2026-08-14",
    status: "clearance_received",
    priority: "urgent",
    priorityReason: "Launch in 9 days — delivery required by 09 Aug.",
    accountsVerified: true,
    packingAssignee: null,
    packingDue: null,
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: null,
  },
  {
    dispatchId: "DSP-000119",
    clearanceId: "CLR-1039",
    paymentRequestId: "PR-000309",
    projectId: "PRJ-000015",
    store: "Clean Craft Lucknow",
    city: "Lucknow",
    items: 39,
    qty: 81,
    clearanceDate: "2026-08-01",
    requiredDelivery: "2026-08-08",
    launchDate: "2026-08-12",
    status: "packing_submitted",
    priority: "high",
    priorityReason: "Packing submitted 1 day ago — review pending before dispatch.",
    accountsVerified: true,
    packingAssignee: "Ramesh Kumar",
    packingDue: "2026-08-04",
    packingEvidence: true,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: "logistics",
  },
  {
    dispatchId: "DSP-000117",
    clearanceId: "CLR-1037",
    paymentRequestId: "PR-000301",
    projectId: "PRJ-000013",
    store: "Clean Craft Surat",
    city: "Surat",
    items: 28,
    qty: 60,
    clearanceDate: "2026-07-29",
    requiredDelivery: "2026-08-05",
    launchDate: "2026-08-09",
    status: "packing_assigned",
    priority: "high",
    priorityReason: "Packing overdue by 1 day against required delivery today.",
    accountsVerified: true,
    packingAssignee: "Sunil Patel",
    packingDue: "2026-08-04",
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: "packing",
  },
  {
    dispatchId: "DSP-000115",
    clearanceId: "CLR-1034",
    paymentRequestId: "PR-000294",
    projectId: "PRJ-000010",
    store: "Clean Craft Kanpur",
    city: "Kanpur",
    items: 31,
    qty: 68,
    clearanceDate: "2026-07-28",
    requiredDelivery: "2026-08-06",
    launchDate: "2026-08-11",
    status: "packing_completed",
    priority: "urgent",
    priorityReason: "Packages approved and ready, but transport is not booked yet.",
    accountsVerified: true,
    packingAssignee: "Ravi Sharma",
    packingDue: "2026-08-03",
    packingEvidence: true,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: "logistics",
  },
  {
    dispatchId: "DSP-000113",
    clearanceId: "CLR-1031",
    paymentRequestId: "PR-000288",
    projectId: "PRJ-000008",
    store: "Clean Craft Nashik",
    city: "Nashik",
    items: 26,
    qty: 55,
    clearanceDate: "2026-07-26",
    requiredDelivery: "2026-08-04",
    launchDate: "2026-08-10",
    status: "booked_externally",
    priority: "high",
    priorityReason: "Booked on Shiprocket — dispatch date to be recorded today.",
    accountsVerified: true,
    packingAssignee: "Ramesh Kumar",
    packingDue: "2026-07-31",
    packingEvidence: true,
    booking: {
      service: "Shiprocket",
      bookingId: "SR-88401992",
      awbOrLr: "AWB-4471290055",
      transporter: "Delhivery Surface",
      vehicle: "MH15-DK-4420",
      driverName: "Imran S.",
      driverMobile: "98•••••210",
      bookingDate: "2026-08-04",
      trackingUrl: "https://shiprocket.co/tracking/AWB-4471290055",
      expectedDelivery: "2026-08-08",
    },
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: "transporter",
  },
  {
    dispatchId: "DSP-000111",
    clearanceId: "CLR-1029",
    paymentRequestId: "PR-000280",
    projectId: "PRJ-000006",
    store: "Clean Craft Nagpur",
    city: "Nagpur",
    items: 24,
    qty: 49,
    clearanceDate: "2026-07-24",
    requiredDelivery: "2026-08-05",
    launchDate: "2026-08-20",
    status: "dispatched",
    priority: "normal",
    priorityReason: "In transit — delivery confirmation expected today.",
    accountsVerified: true,
    packingAssignee: "Sunil Patel",
    packingDue: "2026-07-29",
    packingEvidence: true,
    booking: {
      service: "WheelsEye",
      bookingId: "WE-5520117",
      awbOrLr: "LR-SFX-22087",
      transporter: "Safexpress",
      vehicle: "MH31-CD-7742",
      driverName: "Sandeep R.",
      driverMobile: "97•••••884",
      bookingDate: "2026-08-01",
      dispatchDate: "2026-08-02",
      trackingUrl: "https://wheelseye.com/track/WE-5520117",
      expectedDelivery: "2026-08-05",
    },
    deliveredOn: null,
    proof: false,
    issue: null,
    delayOwner: null,
  },
  {
    dispatchId: "DSP-000109",
    clearanceId: "CLR-1027",
    paymentRequestId: "PR-000272",
    projectId: "PRJ-000004",
    store: "Clean Craft Bhopal",
    city: "Bhopal",
    items: 22,
    qty: 44,
    clearanceDate: "2026-07-20",
    requiredDelivery: "2026-08-02",
    launchDate: "2026-08-08",
    status: "delivery_issue",
    priority: "urgent",
    priorityReason: "Short delivery reported — 2 trolley units missing against billed boxes.",
    accountsVerified: true,
    packingAssignee: "Ravi Sharma",
    packingDue: "2026-07-26",
    packingEvidence: true,
    booking: {
      service: "Other",
      bookingId: "TCI-40911",
      awbOrLr: "LR-TCI-40911",
      transporter: "TCI Freight",
      vehicle: "MP09-AB-3310",
      bookingDate: "2026-07-29",
      dispatchDate: "2026-07-30",
      trackingUrl: "https://tcil.com/track/40911",
      expectedDelivery: "2026-08-02",
    },
    deliveredOn: "2026-08-02",
    proof: true,
    issue: "Short delivery — 2 items missing",
    delayOwner: "transporter",
  },
  {
    dispatchId: "DSP-000107",
    clearanceId: "CLR-1025",
    paymentRequestId: "PR-000265",
    projectId: "PRJ-000002",
    store: "Clean Craft Raipur",
    city: "Raipur",
    items: 19,
    qty: 40,
    clearanceDate: "2026-07-18",
    requiredDelivery: "2026-07-30",
    launchDate: "2026-08-06",
    status: "delivered",
    priority: "normal",
    priorityReason: "Delivered — customer confirmation pending for closure.",
    accountsVerified: true,
    packingAssignee: "Ramesh Kumar",
    packingDue: "2026-07-23",
    packingEvidence: true,
    booking: {
      service: "Shiprocket",
      bookingId: "SR-88300451",
      awbOrLr: "AWB-4470119923",
      transporter: "Ecom Express",
      bookingDate: "2026-07-26",
      dispatchDate: "2026-07-27",
      trackingUrl: "https://shiprocket.co/tracking/AWB-4470119923",
      expectedDelivery: "2026-07-30",
    },
    deliveredOn: "2026-07-30",
    proof: true,
    issue: null,
    delayOwner: null,
  },
  {
    dispatchId: "DSP-000105",
    clearanceId: "CLR-1023",
    paymentRequestId: "PR-000258",
    projectId: "PRJ-000001",
    store: "Clean Craft Ranchi",
    city: "Ranchi",
    items: 21,
    qty: 46,
    clearanceDate: "2026-07-15",
    requiredDelivery: "2026-07-27",
    launchDate: "2026-08-04",
    status: "suspended",
    priority: "urgent",
    priorityReason: "Payment reversal after dispatch planning — Accounts suspended the clearance.",
    accountsVerified: false,
    packingAssignee: "Sunil Patel",
    packingDue: "2026-07-21",
    packingEvidence: true,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: "Accounts clearance suspended (payment reversal)",
    delayOwner: "accounts",
  },
  {
    dispatchId: "DSP-000103",
    clearanceId: "CLR-1021",
    paymentRequestId: "PR-000249",
    projectId: "PRJ-000009",
    store: "Clean Craft Patna",
    city: "Patna",
    items: 25,
    qty: 52,
    clearanceDate: "2026-07-12",
    requiredDelivery: "2026-07-24",
    launchDate: "2026-08-02",
    status: "item_unavailable",
    priority: "high",
    priorityReason: "2 steam-press units unavailable in stores — dispatch on hold.",
    accountsVerified: true,
    packingAssignee: null,
    packingDue: null,
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: "Item unavailable — steam press x2",
    delayOwner: "items",
  },
  {
    dispatchId: "DSP-000101",
    clearanceId: "CLR-1019",
    paymentRequestId: "PR-000241",
    projectId: "PRJ-000007",
    store: "Clean Craft Agra",
    city: "Agra",
    items: 30,
    qty: 63,
    clearanceDate: "2026-07-10",
    requiredDelivery: "2026-07-22",
    launchDate: "2026-07-30",
    status: "packing_correction",
    priority: "high",
    priorityReason: "Packing review failed — photo evidence missing for 4 cartons.",
    accountsVerified: true,
    packingAssignee: "Ravi Sharma",
    packingDue: "2026-07-18",
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: "Packing correction required",
    delayOwner: "packing",
  },
  {
    dispatchId: "DSP-000099",
    clearanceId: "CLR-1017",
    paymentRequestId: "PR-000233",
    projectId: "PRJ-000005",
    store: "Clean Craft Kota",
    city: "Kota",
    items: 18,
    qty: 37,
    clearanceDate: "2026-07-08",
    requiredDelivery: "2026-07-20",
    launchDate: "2026-07-28",
    status: "returned",
    priority: "high",
    priorityReason: "Return initiated — address problem at destination.",
    accountsVerified: true,
    packingAssignee: "Ramesh Kumar",
    packingDue: "2026-07-14",
    packingEvidence: true,
    booking: {
      service: "WheelsEye",
      bookingId: "WE-5510008",
      awbOrLr: "LR-WE-5510008",
      transporter: "VRL Logistics",
      vehicle: "RJ14-GA-2291",
      bookingDate: "2026-07-16",
      dispatchDate: "2026-07-17",
      trackingUrl: "https://wheelseye.com/track/WE-5510008",
      expectedDelivery: "2026-07-20",
    },
    deliveredOn: null,
    proof: false,
    issue: "Address problem — return initiated",
    delayOwner: "franchise",
  },
  {
    dispatchId: "DSP-000097",
    clearanceId: "CLR-1015",
    paymentRequestId: "PR-000228",
    projectId: "PRJ-000003",
    store: "Clean Craft Ludhiana",
    city: "Ludhiana",
    items: 27,
    qty: 58,
    clearanceDate: "2026-07-05",
    requiredDelivery: "2026-07-18",
    launchDate: "2026-07-26",
    status: "closed",
    priority: "normal",
    priorityReason: "Closed after confirmed delivery and store acknowledgement.",
    accountsVerified: true,
    packingAssignee: "Sunil Patel",
    packingDue: "2026-07-11",
    packingEvidence: true,
    booking: {
      service: "Shiprocket",
      bookingId: "SR-88100234",
      awbOrLr: "AWB-4468881100",
      transporter: "Delhivery Surface",
      bookingDate: "2026-07-13",
      dispatchDate: "2026-07-14",
      trackingUrl: "https://shiprocket.co/tracking/AWB-4468881100",
      expectedDelivery: "2026-07-18",
    },
    deliveredOn: "2026-07-18",
    proof: true,
    issue: null,
    delayOwner: null,
  },
  {
    dispatchId: "DSP-000095",
    clearanceId: "CLR-1013",
    paymentRequestId: "PR-000220",
    projectId: "PRJ-000012",
    store: "Clean Craft Gwalior",
    city: "Gwalior",
    items: 23,
    qty: 48,
    clearanceDate: "2026-07-02",
    requiredDelivery: "2026-07-15",
    launchDate: "2026-07-24",
    status: "info_required",
    priority: "normal",
    priorityReason: "Clearance returned to Accounts — item list and quantity mismatch.",
    accountsVerified: false,
    packingAssignee: null,
    packingDue: null,
    packingEvidence: false,
    booking: null,
    deliveredOn: null,
    proof: false,
    issue: "Information required from Accounts",
    delayOwner: "accounts",
  },
];

export const PACKING_STAFF: PackingStaff[] = [
  { id: "PS-01", name: "Ramesh Kumar", initials: "RK", active: 2, dueToday: 1, completed: 34, corrections: 0 },
  { id: "PS-02", name: "Sunil Patel", initials: "SP", active: 3, dueToday: 2, completed: 29, corrections: 1 },
  { id: "PS-03", name: "Ravi Sharma", initials: "RS", active: 2, dueToday: 1, completed: 26, corrections: 2 },
  { id: "PS-04", name: "Meena Devi", initials: "MD", active: 1, dueToday: 0, completed: 18, corrections: 0 },
];

export const STATUS_LABEL: Record<DispatchStatus, string> = {
  clearance_received: "Accounts Clearance Received",
  logistics_accepted: "Logistics Accepted",
  items_checked: "Items Checked",
  packing_assigned: "Packing Assigned",
  packing_submitted: "Packing Waiting for Review",
  packing_completed: "Packing Completed",
  dispatch_planned: "Dispatch Planned",
  booked_externally: "Booked Externally",
  dispatched: "Dispatched",
  delivered: "Delivered",
  closed: "Closed",
  info_required: "Information Required",
  item_unavailable: "Item Unavailable",
  packing_correction: "Packing Correction Required",
  dispatch_delayed: "Dispatch Delayed",
  delivery_issue: "Delivery Issue",
  returned: "Returned",
  cancelled: "Cancelled",
  suspended: "Clearance Suspended",
};

export const STATUS_TONE: Record<DispatchStatus, "good" | "info" | "warn" | "bad" | "muted"> = {
  clearance_received: "warn",
  logistics_accepted: "info",
  items_checked: "info",
  packing_assigned: "info",
  packing_submitted: "warn",
  packing_completed: "good",
  dispatch_planned: "info",
  booked_externally: "info",
  dispatched: "good",
  delivered: "good",
  closed: "good",
  info_required: "warn",
  item_unavailable: "bad",
  packing_correction: "warn",
  dispatch_delayed: "warn",
  delivery_issue: "bad",
  returned: "bad",
  cancelled: "muted",
  suspended: "bad",
};

export const DELAY_OWNER_LABEL: Record<DelayOwner, string> = {
  accounts: "Accounts",
  items: "Item availability",
  packing: "Packing Staff",
  transporter: "Transporter",
  franchise: "Franchise customer",
  logistics: "Logistics (own)",
};
