import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Activity, TrendingUp } from "lucide-react";
import { SectionHead } from "./ui";
import { ANALYTICS_WEEKS, TOP_POSTS } from "./data";

export function SmmAnalyticsPage() {
  const last = ANALYTICS_WEEKS[ANALYTICS_WEEKS.length - 1];
  return (
    <div className="space-y-4">
      <SectionHead title="Analytics" sub="Reach, engagement, follower growth and leads generated by content." />

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { l: "Reach (last week)", v: `${(last.reach / 1000).toFixed(0)}K` },
          { l: "Engagements", v: last.engagement.toLocaleString("en-IN") },
          { l: "New Followers", v: `+${last.followers}` },
          { l: "Leads Generated", v: String(last.leads) },
        ].map((s) => (
          <Card key={s.l}>
            <CardContent className="p-4">
              <div className="text-xs text-muted-foreground">{s.l}</div>
              <div className="text-3xl font-bold tabular-nums mt-1">{s.v}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid lg:grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <Activity className="w-4 h-4 text-primary" /> Reach by week
            </CardTitle>
          </CardHeader>
          <CardContent className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={ANALYTICS_WEEKS}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis dataKey="week" fontSize={12} />
                <YAxis fontSize={12} tickFormatter={(v) => `${v / 1000}K`} />
                <Tooltip formatter={(v: number) => v.toLocaleString("en-IN")} />
                <Area dataKey="reach" stroke="hsl(var(--primary))" fill="hsl(var(--primary))" fillOpacity={0.2} />
              </AreaChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-primary" /> Leads from social by week
            </CardTitle>
          </CardHeader>
          <CardContent className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={ANALYTICS_WEEKS}>
                <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                <XAxis dataKey="week" fontSize={12} />
                <YAxis fontSize={12} />
                <Tooltip />
                <Bar dataKey="leads" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-3"><CardTitle className="text-base">Top performing content</CardTitle></CardHeader>
        <CardContent className="space-y-2">
          {TOP_POSTS.map((p) => (
            <div key={p.title} className="border rounded-md p-3 flex items-center justify-between gap-3 flex-wrap">
              <div>
                <div className="text-sm font-medium">{p.title}</div>
                <Badge variant="outline" className="mt-1">{p.platform}</Badge>
              </div>
              <div className="flex gap-6 text-right">
                <div>
                  <div className="text-[11px] text-muted-foreground">Reach</div>
                  <div className="text-sm font-semibold tabular-nums">{p.reach}</div>
                </div>
                <div>
                  <div className="text-[11px] text-muted-foreground">Engagement</div>
                  <div className="text-sm font-semibold tabular-nums">{p.engagement}</div>
                </div>
                <div>
                  <div className="text-[11px] text-muted-foreground">Leads</div>
                  <div className="text-sm font-semibold tabular-nums">{p.leads}</div>
                </div>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
