export type AssetStatus = "Draft" | "Awaiting Approval" | "Approved" | "Replaced" | "Archived";

export type AssetCategory =
  | "Brand Guidelines"
  | "Logos"
  | "Fonts & Colours"
  | "Video Templates"
  | "Intro & Outro"
  | "Music & Sound"
  | "Graphics & Icons"
  | "Thumbnails"
  | "Subtitles & Captions"
  | "Reference Videos";

export const ASSET_CATEGORIES: AssetCategory[] = [
  "Brand Guidelines",
  "Logos",
  "Fonts & Colours",
  "Video Templates",
  "Intro & Outro",
  "Music & Sound",
  "Graphics & Icons",
  "Thumbnails",
  "Subtitles & Captions",
  "Reference Videos",
];

export const ASSET_BRANDS = [
  "Clean Craft",
  "GILM",
  "Bombay Towel Co.",
  "Clean Craft — Franchise",
  "Clean Craft Institute",
];

export type LibraryAsset = {
  id: string;
  name: string;
  brand: string;
  category: AssetCategory;
  fileType: string;
  version: string;
  updated: string;
  updatedOrder: number;
  status: AssetStatus;
  preview: string;
  description: string;
  permitted: string[];
  prohibited: string[];
  platform: string;
  contentType: string;
  dimensions: string;
  format: string;
  language: string;
  uploadedBy: string;
  archived: boolean;
  doNotUse?: boolean;
  history: { version: string; status: AssetStatus; on: string; by: string; note: string }[];
};

export const LIBRARY_ASSETS: LibraryAsset[] = [
  {
    id: "AS-101",
    name: "Clean Craft primary logo — light background",
    brand: "Clean Craft",
    category: "Logos",
    fileType: "PNG",
    version: "v4",
    updated: "2 days ago",
    updatedOrder: 2,
    status: "Approved",
    preview: "🧼",
    description: "Primary horizontal logo lockup for use on white and light surfaces across all video content.",
    permitted: ["Video intros and outros", "Corner watermark", "Thumbnails", "End cards"],
    prohibited: ["Do not stretch or rotate", "Do not recolour", "Never place on busy footage without a scrim"],
    platform: "All platforms",
    contentType: "All content types",
    dimensions: "4000 x 1200 px",
    format: "PNG (transparent)",
    language: "English",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [
      { version: "v4", status: "Approved", on: "2 days ago", by: "Brand Manager", note: "Updated wordmark spacing" },
      { version: "v3", status: "Replaced", on: "Mar 2026", by: "Brand Manager", note: "Old spacing — do not use" },
    ],
  },
  {
    id: "AS-102",
    name: "Clean Craft logo — dark background",
    brand: "Clean Craft",
    category: "Logos",
    fileType: "SVG",
    version: "v3",
    updated: "1 week ago",
    updatedOrder: 7,
    status: "Approved",
    preview: "🌙",
    description: "Reversed white logo for dark footage, night shots and dark-mode end cards.",
    permitted: ["Dark footage overlays", "Reels with dark grade"],
    prohibited: ["Do not use on light footage", "Do not add drop shadows"],
    platform: "Instagram + YouTube",
    contentType: "Reel, Short Video",
    dimensions: "Vector",
    format: "SVG",
    language: "English",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v3", status: "Approved", on: "1 week ago", by: "Brand Manager", note: "Vector cleanup" }],
  },
  {
    id: "AS-103",
    name: "Clean Craft logo — 2024 old mark",
    brand: "Clean Craft",
    category: "Logos",
    fileType: "PNG",
    version: "v2",
    updated: "Jan 2026",
    updatedOrder: 200,
    status: "Archived",
    preview: "🚫",
    description: "Superseded 2024 logo mark. Retained only because it appears in already published videos.",
    permitted: ["Reference only for archived published videos"],
    prohibited: ["Never use in any new edit"],
    platform: "—",
    contentType: "—",
    dimensions: "2400 x 900 px",
    format: "PNG",
    language: "English",
    uploadedBy: "Brand Manager",
    archived: true,
    doNotUse: true,
    history: [{ version: "v2", status: "Archived", on: "Jan 2026", by: "Brand Manager", note: "Replaced by v4 lockup" }],
  },
  {
    id: "AS-104",
    name: "Clean Craft brand guideline book",
    brand: "Clean Craft",
    category: "Brand Guidelines",
    fileType: "PDF",
    version: "v6",
    updated: "Today",
    updatedOrder: 0,
    status: "Approved",
    preview: "📘",
    description: "Complete brand system: logo, clear space, colour, type, subtitle and thumbnail rules for video.",
    permitted: ["Reference for every edit", "Share with new editors"],
    prohibited: ["Do not share outside the company", "Do not edit the PDF"],
    platform: "All platforms",
    contentType: "All content types",
    dimensions: "A4, 48 pages",
    format: "PDF",
    language: "English",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [
      { version: "v6", status: "Approved", on: "Today", by: "Brand Manager", note: "Added Reels subtitle safe area" },
      { version: "v5", status: "Replaced", on: "Feb 2026", by: "Brand Manager", note: "Superseded" },
    ],
  },
  {
    id: "AS-105",
    name: "Franchise offer reel template",
    brand: "Clean Craft — Franchise",
    category: "Video Templates",
    fileType: "MOGRT",
    version: "v5",
    updated: "Yesterday",
    updatedOrder: 1,
    status: "Approved",
    preview: "🎬",
    description: "9:16 franchise offer template with hook card, offer card and franchise enquiry end card.",
    permitted: ["Franchise ads", "Franchise reels"],
    prohibited: ["Do not change the offer card layout", "Do not alter the CTA wording"],
    platform: "Meta + YouTube",
    contentType: "Advertisement",
    dimensions: "1080 x 1920 px",
    format: "MOGRT (Premiere Pro)",
    language: "Hindi + English",
    uploadedBy: "Social Media Account Manager",
    archived: false,
    history: [
      { version: "v5", status: "Approved", on: "Yesterday", by: "SMM", note: "New ₹4.9L offer card" },
      { version: "v4", status: "Replaced", on: "Jul 2026", by: "SMM", note: "Old ₹4.5L card — do not use" },
    ],
  },
  {
    id: "AS-106",
    name: "Clean Craft intro sting — 3s",
    brand: "Clean Craft",
    category: "Intro & Outro",
    fileType: "MP4",
    version: "v2",
    updated: "5 days ago",
    updatedOrder: 5,
    status: "Approved",
    preview: "▶️",
    description: "Three-second animated intro sting with logo reveal and audio whoosh.",
    permitted: ["Long videos", "Training videos"],
    prohibited: ["Do not use on 6s bumper ads", "Do not slow down or trim"],
    platform: "YouTube",
    contentType: "Long Video, Training Video",
    dimensions: "1920 x 1080 px",
    format: "MP4, H.264",
    language: "—",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v2", status: "Approved", on: "5 days ago", by: "Brand Manager", note: "Audio remastered" }],
  },
  {
    id: "AS-107",
    name: "Approved music library — upbeat pack",
    brand: "Clean Craft",
    category: "Music & Sound",
    fileType: "WAV",
    version: "v3",
    updated: "3 days ago",
    updatedOrder: 3,
    status: "Approved",
    preview: "🎵",
    description: "Twelve licensed upbeat tracks cleared for paid and organic use, with loop points marked.",
    permitted: ["Reels", "Ads", "Store videos"],
    prohibited: ["No trending audio from social apps", "Never exceed -18dB under voice"],
    platform: "All platforms",
    contentType: "All content types",
    dimensions: "—",
    format: "WAV + MP3",
    language: "Instrumental",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v3", status: "Approved", on: "3 days ago", by: "Brand Manager", note: "3 new tracks added" }],
  },
  {
    id: "AS-108",
    name: "Subtitle style preset — Hindi + English",
    brand: "Clean Craft",
    category: "Subtitles & Captions",
    fileType: "PRESET",
    version: "v4",
    updated: "4 days ago",
    updatedOrder: 4,
    status: "Approved",
    preview: "💬",
    description: "Burned-in caption preset: Poppins SemiBold 48pt, white with 60% black pill, two lines maximum.",
    permitted: ["All vertical content", "Testimonials"],
    prohibited: ["No all-caps captions", "Never cover the lower 14% platform UI"],
    platform: "Instagram + Facebook",
    contentType: "Reel, Testimonial",
    dimensions: "1080 x 1920 safe area",
    format: "Premiere preset",
    language: "Hindi + English",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v4", status: "Approved", on: "4 days ago", by: "Brand Manager", note: "Larger pill padding" }],
  },
  {
    id: "AS-109",
    name: "Thumbnail grid template — YouTube",
    brand: "Clean Craft",
    category: "Thumbnails",
    fileType: "PSD",
    version: "v2",
    updated: "1 week ago",
    updatedOrder: 8,
    status: "Approved",
    preview: "🖼️",
    description: "1280x720 thumbnail layout with title zone, face zone and brand bar.",
    permitted: ["YouTube long videos", "Website videos"],
    prohibited: ["No more than 5 words of title text", "Do not cover the brand bar"],
    platform: "YouTube",
    contentType: "Long Video",
    dimensions: "1280 x 720 px",
    format: "PSD",
    language: "English",
    uploadedBy: "Social Media Account Manager",
    archived: false,
    history: [{ version: "v2", status: "Approved", on: "1 week ago", by: "SMM", note: "Brand bar moved down" }],
  },
  {
    id: "AS-110",
    name: "GILM product icon set",
    brand: "GILM",
    category: "Graphics & Icons",
    fileType: "SVG",
    version: "v1",
    updated: "6 days ago",
    updatedOrder: 6,
    status: "Approved",
    preview: "✨",
    description: "Line icon set for GILM garment care explainers and process animations.",
    permitted: ["GILM explainers", "Process animations"],
    prohibited: ["Do not mix with Clean Craft icon set"],
    platform: "Instagram",
    contentType: "Educational Video",
    dimensions: "Vector",
    format: "SVG",
    language: "—",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v1", status: "Approved", on: "6 days ago", by: "Brand Manager", note: "First release" }],
  },
  {
    id: "AS-111",
    name: "Bombay Towel Co. colour & font sheet",
    brand: "Bombay Towel Co.",
    category: "Fonts & Colours",
    fileType: "PDF",
    version: "v2",
    updated: "2 weeks ago",
    updatedOrder: 14,
    status: "Approved",
    preview: "🎨",
    description: "Palette and typography sheet for Bombay Towel Co. product films.",
    permitted: ["Product videos", "Thumbnails"],
    prohibited: ["Do not substitute fonts", "No gradients on type"],
    platform: "Website + Instagram",
    contentType: "Product Video",
    dimensions: "A4",
    format: "PDF",
    language: "English",
    uploadedBy: "Brand Manager",
    archived: false,
    history: [{ version: "v2", status: "Approved", on: "2 weeks ago", by: "Brand Manager", note: "New towel-teal added" }],
  },
  {
    id: "AS-112",
    name: "Winning ad reference — July franchise cut",
    brand: "Clean Craft — Franchise",
    category: "Reference Videos",
    fileType: "MP4",
    version: "v1",
    updated: "3 weeks ago",
    updatedOrder: 21,
    status: "Approved",
    preview: "🏆",
    description: "Best-performing franchise ad from July. Use as the pacing and hook benchmark.",
    permitted: ["Reference only"],
    prohibited: ["Do not reuse footage without approval"],
    platform: "Meta",
    contentType: "Advertisement",
    dimensions: "1080 x 1920 px",
    format: "MP4",
    language: "Hindi",
    uploadedBy: "Social Media Account Manager",
    archived: false,
    history: [{ version: "v1", status: "Approved", on: "3 weeks ago", by: "SMM", note: "Archived winner" }],
  },
  {
    id: "AS-113",
    name: "Institute admission template (pending sign-off)",
    brand: "Clean Craft Institute",
    category: "Video Templates",
    fileType: "MOGRT",
    version: "v1",
    updated: "Today",
    updatedOrder: 0,
    status: "Awaiting Approval",
    preview: "🎓",
    description: "New admission-season template awaiting brand sign-off. Not downloadable until approved.",
    permitted: ["—"],
    prohibited: ["Not for use until approved"],
    platform: "Instagram",
    contentType: "Advertisement",
    dimensions: "1080 x 1920 px",
    format: "MOGRT",
    language: "English",
    uploadedBy: "Social Media Account Manager",
    archived: false,
    history: [{ version: "v1", status: "Awaiting Approval", on: "Today", by: "SMM", note: "Sent for brand review" }],
  },
];

export const BRAND_COLOURS = [
  { name: "Craft Blue", hex: "#0F4C81", rgb: "15, 76, 129", cmyk: "88, 41, 0, 49" },
  { name: "Fresh Teal", hex: "#14B8A6", rgb: "20, 184, 166", cmyk: "89, 0, 10, 28" },
  { name: "Signal Amber", hex: "#F59E0B", rgb: "245, 158, 11", cmyk: "0, 36, 96, 4" },
  { name: "Ink", hex: "#0B1220", rgb: "11, 18, 32", cmyk: "66, 44, 0, 87" },
  { name: "Cloud", hex: "#F5F7FA", rgb: "245, 247, 250", cmyk: "2, 1, 0, 2" },
];

export const GUIDELINE_BLOCKS: { title: string; items: string[] }[] = [
  {
    title: "Logo placement",
    items: [
      "Vertical video: top-right, inside the safe area",
      "Horizontal video: bottom-right, visible for the full run",
      "Never place the logo over a face or subtitle pill",
    ],
  },
  {
    title: "Logo clear space",
    items: [
      "Minimum clear space equals the height of the 'C' on all sides",
      "Minimum on-screen width: 12% of frame width",
    ],
  },
  {
    title: "Approved logo versions",
    items: ["Primary lockup v4 (light)", "Reversed white v3 (dark)", "2024 mark — archived, Do Not Use"],
  },
  {
    title: "Approved fonts",
    items: ["Poppins SemiBold — titles and cards", "Inter Regular — body and lower thirds", "No system font substitutes"],
  },
  {
    title: "Subtitle style",
    items: [
      "Poppins SemiBold 48pt, white on 60% black pill",
      "Maximum two lines, clear of the lower 14% platform UI",
      "Hindi + English on all vertical content",
    ],
  },
  {
    title: "Thumbnail style",
    items: ["1280x720, max 5 words of title text", "Face in the left third", "Brand bar always visible"],
  },
  {
    title: "Intro and outro rules",
    items: [
      "3s intro sting on long and training videos only",
      "No intro on 6s bumpers or performance ads",
      "End card holds for 2s minimum",
    ],
  },
  {
    title: "Music guidelines",
    items: [
      "Approved licensed library only — no trending social audio",
      "Music sits at -18dB under voice",
      "Fade out over the last 1.5s",
    ],
  },
  {
    title: "Call-to-action format",
    items: [
      "Franchise content: franchise enquiry CTA + end card",
      "Store content: follow + store locator end card",
      "CTA text never changes wording without SMM approval",
    ],
  },
];

export const VIDEO_SPECS = [
  {
    platform: "Instagram Reels",
    aspect: "9:16",
    resolution: "1080 x 1920",
    duration: "15–45s",
    format: "MP4, H.264",
    maxSize: "Max file size placeholder",
    safeArea: "Keep captions clear of lower 14% and top 10%",
    thumbnail: "Cover frame required",
  },
  {
    platform: "Facebook Reels",
    aspect: "9:16",
    resolution: "1080 x 1920",
    duration: "15–60s",
    format: "MP4, H.264",
    maxSize: "Max file size placeholder",
    safeArea: "Lower 16% reserved for platform UI",
    thumbnail: "Cover frame required",
  },
  {
    platform: "YouTube Shorts",
    aspect: "9:16",
    resolution: "1080 x 1920",
    duration: "Under 60s",
    format: "MP4, H.264",
    maxSize: "Max file size placeholder",
    safeArea: "Avoid lower 18% (title + actions)",
    thumbnail: "Optional",
  },
  {
    platform: "YouTube Long Videos",
    aspect: "16:9",
    resolution: "1920 x 1080",
    duration: "3–10 min",
    format: "MP4, H.264 high bitrate",
    maxSize: "Max file size placeholder",
    safeArea: "Captions above lower 10%",
    thumbnail: "1280 x 720 thumbnail mandatory",
  },
  {
    platform: "LinkedIn Videos",
    aspect: "1:1 or 16:9",
    resolution: "1080 x 1080 / 1920 x 1080",
    duration: "30–90s",
    format: "MP4, H.264",
    maxSize: "Max file size placeholder",
    safeArea: "Burned-in subtitles mandatory",
    thumbnail: "Cover frame recommended",
  },
  {
    platform: "Advertisements",
    aspect: "9:16 + 1:1 + 16:9",
    resolution: "1080 x 1920 / 1080 x 1080 / 1920 x 1080",
    duration: "6s / 15s / 30s",
    format: "MP4, H.264, under 200MB",
    maxSize: "Max file size placeholder",
    safeArea: "Offer card inside centre safe area",
    thumbnail: "Static variant required",
  },
  {
    platform: "Website Videos",
    aspect: "16:9",
    resolution: "1920 x 1080",
    duration: "45–120s",
    format: "MP4, H.264 web-optimised",
    maxSize: "Max file size placeholder",
    safeArea: "No platform UI — full frame usable",
    thumbnail: "Poster frame required",
  },
];

export const REQUEST_TYPES = [
  "Missing logo",
  "New template",
  "Music",
  "Product image",
  "Reference video",
  "Correct font",
  "Other asset",
];
