/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVideoEditorRouteImport } from './routes/_authenticated/video-editor'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMySalesRouteImport } from './routes/_authenticated/my-sales'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedHrHeadRouteImport } from './routes/_authenticated/hr-head'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads_.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoEditorRoute =
  AuthenticatedVideoEditorRouteImport.update({
    id: '/video-editor',
    path: '/video-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySalesRoute = AuthenticatedMySalesRouteImport.update({
  id: '/my-sales',
  path: '/my-sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrHeadRoute = AuthenticatedHrHeadRouteImport.update({
  id: '/hr-head',
  path: '/hr-head',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads_/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr-head': typeof AuthenticatedHrHeadRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/master': typeof AuthenticatedMasterRoute
  '/my-sales': typeof AuthenticatedMySalesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/video-editor': typeof AuthenticatedVideoEditorRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr-head': typeof AuthenticatedHrHeadRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/master': typeof AuthenticatedMasterRoute
  '/my-sales': typeof AuthenticatedMySalesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/video-editor': typeof AuthenticatedVideoEditorRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hr-head': typeof AuthenticatedHrHeadRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/master': typeof AuthenticatedMasterRoute
  '/_authenticated/my-sales': typeof AuthenticatedMySalesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/video-editor': typeof AuthenticatedVideoEditorRoute
  '/_authenticated/leads_/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/hr-head'
    | '/leads'
    | '/master'
    | '/my-sales'
    | '/payments'
    | '/projects'
    | '/stores'
    | '/tasks'
    | '/users'
    | '/video-editor'
    | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/hr-head'
    | '/leads'
    | '/master'
    | '/my-sales'
    | '/payments'
    | '/projects'
    | '/stores'
    | '/tasks'
    | '/users'
    | '/video-editor'
    | '/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/complaints'
    | '/_authenticated/dashboard'
    | '/_authenticated/hr-head'
    | '/_authenticated/leads'
    | '/_authenticated/master'
    | '/_authenticated/my-sales'
    | '/_authenticated/payments'
    | '/_authenticated/projects'
    | '/_authenticated/stores'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/_authenticated/video-editor'
    | '/_authenticated/leads_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/video-editor': {
      id: '/_authenticated/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof AuthenticatedVideoEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-sales': {
      id: '/_authenticated/my-sales'
      path: '/my-sales'
      fullPath: '/my-sales'
      preLoaderRoute: typeof AuthenticatedMySalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr-head': {
      id: '/_authenticated/hr-head'
      path: '/hr-head'
      fullPath: '/hr-head'
      preLoaderRoute: typeof AuthenticatedHrHeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads_/$id': {
      id: '/_authenticated/leads_/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHrHeadRoute: typeof AuthenticatedHrHeadRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRoute
  AuthenticatedMySalesRoute: typeof AuthenticatedMySalesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVideoEditorRoute: typeof AuthenticatedVideoEditorRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHrHeadRoute: AuthenticatedHrHeadRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRoute,
  AuthenticatedMySalesRoute: AuthenticatedMySalesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVideoEditorRoute: AuthenticatedVideoEditorRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
